# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scan-it' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionBarcodeModel'
    pod 'BarcodeScanner'
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage'
  # Pods for scan-it

  target 'scan-itTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scan-itUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
